2 little typos
medooze/rtmp-server-node pull request #20
Opened 2023-10-16 01:24 UTC by mildsunrise

normally i wouldn't care about a typo if it's on an API, but it must be called `detach()` to implement the media server API correctly

2023-10-24 13:56 UTC, murillo128 commented on lib/IncomingStreamBridge.js
> +	detach()
can we keep the `dettach` as an alias to `detach` and mark it as deprecated?

2023-10-30 15:33 UTC, murillo128 requested changes

2023-10-30 16:35 UTC, mildsunrise commented on lib/IncomingStreamBridge.js
> +	detach()
done

2023-10-30 16:35 UTC, mildsunrise commented
rebased, this should be ready to go

2023-10-30 17:17 UTC, murillo128 approved these changes
lgtm

2023-10-30 17:18 UTC, merged