Add getRTT function
medooze/rtmp-server-node pull request #24
Opened 2023-11-23 10:28 UTC by harryz2000

2023-11-23 10:53 UTC, murillo128 requested changes

2023-11-23 10:53 UTC, murillo128 commented on lib/IncomingStreamBridge.js
> +	getRTT()
please, add this as an stats of the IncomingStreamTrackBridge.getStats() and IncomingStreamTrackBridge.getStatsAsync() instead

https://github.com/medooze/rtmp-server-node/blob/master/lib/IncomingStreamTrackBridge.js#L182

2023-11-23 22:24 UTC, harryz2000 commented on lib/IncomingStreamBridge.js
> +	getRTT()
The idea was the RTT is for the stream. I think some stats could be stream/connection related. If we add it to IncomingStreamTrackBridge, it probably means we should add RTT to MediaFrameListener bridge. But both tracks will have same value. Should we do that?

2023-11-24 01:52 UTC, harryz2000 commented
I changed to let the IncomingStreamTrackBridge to getRTT(). And there is no getStatsAsync() at the moment. So only change the getStats() for now. After this, the publisher change should not needed for RTMP.

2023-11-24 09:22 UTC, murillo128 requested changes

2023-11-24 09:22 UTC, murillo128 commented on lib/IncomingStreamBridge.js
> +const Stream = require("./Stream");
why is this needed?

2023-11-24 09:22 UTC, murillo128 commented on lib/IncomingStreamBridge.js
> +		this.tracks.set("audio",new IncomingStreamTrackBridge("audio","audio",SharedPointer(this.bridge.GetAudio()), this));
better pass `this.stream` directly

2023-11-24 09:22 UTC, murillo128 commented on lib/IncomingStreamBridge.js
> +	getStream()
don't expose the native objects in the api, please remove

2023-11-24 09:22 UTC, murillo128 commented on lib/IncomingStreamTrackBridge.js
> +		/** @type {IncomingStreamBridge} */ stream)
use native stream instead

2023-11-24 09:22 UTC, murillo128 commented on lib/IncomingStreamTrackBridge.js
> +		/** @type {IncomingStreamBridge} */ stream)
also, remove the refence in the `stop()` method so it can be garbage collected sooner

2023-11-24 09:22 UTC, murillo128 commented on lib/IncomingStreamTrackBridge.js
> +		const rtt = this.stream.getStream() ? this.stream.getStream().stream.GetRTT() : 0;
```suggestion
		const rtt = this.stream.GetRTT();
```

it is fine to throw an exception if `this.stream` is null

2023-11-24 09:22 UTC, murillo128 commented on lib/IncomingStreamBridge.js
> +		this.tracks.set("audio",new IncomingStreamTrackBridge("audio","audio",SharedPointer(this.bridge.GetAudio()), this));
```suggestion
		this.tracks.set("audio",new IncomingStreamTrackBridge("audio","audio",SharedPointer(this.bridge.GetAudio()), this.stream));
```

2023-11-24 09:22 UTC, murillo128 commented on lib/IncomingStreamBridge.js
> +		this.tracks.set("video",new IncomingStreamTrackBridge("video","video",SharedPointer(this.bridge.GetVideo()), this));
```suggestion
		this.tracks.set("video",new IncomingStreamTrackBridge("video","video",SharedPointer(this.bridge.GetVideo()), this.stream));
```

2023-11-24 09:22 UTC, murillo128 commented on lib/IncomingStreamTrackBridge.js
> +		/** @type {IncomingStreamBridge} */ stream)
```suggestion
		/** @type {SharedPointer.Proxy<Native.RTMPNetStreamImpl>} */ stream)
```

2023-11-24 10:50 UTC, harryz2000 commented on lib/IncomingStreamBridge.js
> +const Stream = require("./Stream");
This is just for type info. Same use as IncomingStreamTrackBridge

2023-11-24 10:52 UTC, harryz2000 commented on lib/IncomingStreamBridge.js
> +		this.tracks.set("audio",new IncomingStreamTrackBridge("audio","audio",SharedPointer(this.bridge.GetAudio()), this));
this.stream is not defined until it is attached. We cannot use it directly.

2023-11-24 10:58 UTC, harryz2000 commented on lib/IncomingStreamBridge.js
> +	getStream()
Then I would need to add a function to IncomingStreamTrackBridge, i.e. SetStream() and called when stream is attached/dettached.

2023-11-24 11:32 UTC, murillo128 commented on lib/IncomingStreamBridge.js
> +		this.tracks.set("audio",new IncomingStreamTrackBridge("audio","audio",SharedPointer(this.bridge.GetAudio()), this));
ok, i missed that, fine with this approach then

2023-11-24 11:33 UTC, murillo128 commented on lib/IncomingStreamBridge.js
> +	getStream()
let's get back the `getRTT()` back then and use from in the track bridge

2023-11-24 11:37 UTC, harryz2000 commented on lib/IncomingStreamBridge.js
> +	getStream()
I just made a commit. Please have a look. I can revert to the getRTT() version if you think that one is better.

2023-11-24 11:38 UTC, murillo128 commented on lib/IncomingStreamBridge.js
> +	getStream()
yes, lets use the getRTT better, sorry for the back and forth

2023-11-24 11:41 UTC, harryz2000 commented on lib/IncomingStreamBridge.js
> +	getStream()
No worries at all. The getRTT() version would need publisher change. Are you OK with that?

2023-11-28 07:45 UTC, murillo128 commented on lib/IncomingStreamBridge.js
> +	getStream()
I think I explained myself pooorly again. 
I would like the RTT to be both IncomingStreamTrackBridge stats and in the IncomingStreamBridge, and use internally the IncomingStreamBridge.getRTT by IncomingStreamTrackBridge  instead of calling the native object

2023-11-28 09:55 UTC, harryz2000 commented on lib/IncomingStreamBridge.js
> +	getStream()
No problem. I see. You want to still put RTT to each track. Will do.

2023-11-28 10:27 UTC, harryz2000 commented
@murillo128 Just committed one change. Please see if this is what you expected. Thanks

2023-11-29 11:00 UTC, murillo128 approved these changes
lgtm

2023-11-29 11:00 UTC, merged