Report RTMP client connection error
medooze/rtmp-server-node pull request #42
Opened 2024-06-13 23:41 UTC by harryz2000

2024-06-14 07:06 UTC, murillo128 requested changes

2024-06-14 07:06 UTC, murillo128 commented on src/RTMPClientConnectionImpl.i
> +					onError(this, ErrorCode::PublishCommandFailed);
we should not send a client wide error if the `Publish` cmd has an error. Let's make the Publish take a promise as input as  CreateStream/DeleteStream instead.

2024-06-14 07:06 UTC, murillo128 commented on lib/ClientConnection.js
> +		this.onerror = (/** @type {Number} */errorCode) =>
should we have a different error handler or just add the reason code to the stopped event as in websocket?

https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent/code

@mildsunrise wdyt?

2024-06-14 07:23 UTC, harryz2000 commented on src/RTMPClientConnectionImpl.i
> +					onError(this, ErrorCode::PublishCommandFailed);
Yep. Will do.

2024-06-14 07:41 UTC, harryz2000 commented on lib/ClientConnection.js
> +		this.onerror = (/** @type {Number} */errorCode) =>
I assume you meant combine ondisconnect and onerror together? what do you mean the stopped event? The ResourceEntry.stop()?

2024-06-17 09:36 UTC, harryz2000 commented on src/RTMPClientConnectionImpl.i
> +					onError(this, ErrorCode::PublishCommandFailed);
It appears the server wouldn't repond _error/_result. The server would return onStatus instead. Therefore, this callback wouldn't be called. I would revert this change.

> "The server responds with the onStatus command to mark the beginning of publish."

2024-06-18 06:51 UTC, murillo128 approved these changes
lgtm

2024-06-19 13:53 UTC, mildsunrise commented on lib/ClientConnection.js
> +		this.onerror = (/** @type {Number} */errorCode) =>
we can do as websocket then, yeah

2024-06-19 18:52 UTC, murillo128 requested changes
please add tests

2024-06-20 06:39 UTC, murillo128 approved these changes
lgtm

2024-06-20 23:11 UTC, merged